import { ToastContainer } from "react-toastify";
import NavBar from "./components/NavBar";
import "./globals.css";
import { Fraunces } from "next/font/google";
import Footer from "./components/Footer";

const fraunces = Fraunces({ subsets: ["latin"], variable: "--font-fraunces" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`h-full antialiased ${fraunces.variable}`}
    >
      <body className="min-h-full flex flex-col">
        <NavBar />
        {children}
        <Footer />
        <ToastContainer />
      </body>
    </html>
  );
}
